DOMAIN = "cyrus_one"

CONF_BLE_NAME = "ble_name"

CYRUS_MANUFACTURER = "Cyrus Audio Ltd"

MODEL_CYRUS_ONE = "Cyrus ONE"
MODEL_CYRUS_ONE_HD = "Cyrus ONE HD"

GATT_SERVICE_UUID = "bc2f4cc6-aaef-4351-9034-d66268e328f0"
GATT_DATA_CHARACTERISTIC_UUID = "06d1e5e7-79ad-4a71-8faa-373789f7d93c"

BLE_MESSAGE_START = 0x40
BLE_MESSAGE_FILLER_BYTE = 0x2B
BLE_MESSAGE_END = 0x25

BLE_VALUE_TRUE = b"1"
BLE_VALUE_FALSE = b"0"

BLE_COMMANDS_DELAY = 0.1

CMD_FETCH = 0x46
CMD_MUTE = 0x4D
CMD_VOLUME = 0x56
CMD_SOURCE = 0x49
CMD_BALANCE = 0x58
CMD_AV_DIRECT = 0x41
CMD_BRIGHTNESS = 0x42
CMD_DAC_PRESENCE = 0x44
CMD_HEADPHONE = 0x48
CMD_SW_VERSION = 0x54
CMD_SERIAL_NUMBER = 0x53

PAYLOAD_BRIGHTNESS_UP = 0x2B
PAYLOAD_BRIGHTNESS_DOWN = 0x2D

SOURCE_BLUETOOTH = "Bluetooth"
SOURCE_PHONO = "Phono"
SOURCE_OPTICAL = "Optical"
SOURCE_SPDIF = "SPDIF"
SOURCE_AUX3 = "AUX 3"
SOURCE_AUX4 = "AUX 4"
SOURCE_AUX5 = "AUX 5"
SOURCE_AUX6 = "AUX 6"
SOURCE_AUX7 = "AUX 7"
SOURCE_AV = "AV"
SOURCE_USB = "USB"

SOURCES_CYRUS_ONE = (
    SOURCE_BLUETOOTH,
    SOURCE_PHONO,
    SOURCE_AUX3,
    SOURCE_AUX4,
    SOURCE_AUX5,
    SOURCE_AV,
)

SOURCES_CYRUS_ONE_HD = (
    SOURCE_BLUETOOTH,
    SOURCE_USB,
    SOURCE_OPTICAL,
    SOURCE_SPDIF,
    SOURCE_PHONO,
    SOURCE_AUX6,
    SOURCE_AUX7,
    SOURCE_AV,
)
